name: app.rynest.aasi
description: A Examination App for AASI

version: 1.0.10+11

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  animations: ^2.0.8
  camera: ^0.10.6
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.2
  dio: ^5.4.0
  dropdown_search: ^5.0.6
  # firebase_core: ^2.4.1
  # firebase_messaging: ^14.2.1
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_html: ^3.0.0-alpha.6
  flutter_local_notifications: ^17.2.2
  flutter_localizations:
    sdk: flutter
  # flutter_native_image: ^0.0.6+1
  flutter_image_compress: ^2.3.0
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.6.0
  get: ^4.6.5
  google_fonts: ^6.1.0
  # googleapis_auth: ^1.3.1
  image: ^4.1.3
  image_cropper: ^8.0.1
  image_picker: ^1.0.4
  injectable: ^2.1.0
  intl: ^0.19.0
  logger: ^1.1.0
  package_info_plus: ^8.0.2
  photo_view: ^0.15.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.2
  stacked: ^3.4.1
  stacked_services: ^1.3.0
  transparent_image: ^2.0.1
  url_launcher: ^6.2.1
  google_mlkit_text_recognition: ^0.14.0
  google_mlkit_commons: ^0.9.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.1.6
  stacked_generator: ^1.5.1

icons_launcher:
  platforms:
    android:
      enable: true
      image_path: "assets/icons/app-icon.png"
    ios:
      enable: true
      image_path: "assets/icons/app-icon-ios.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/rives/
    - assets/translations/
