// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyD16Iu-3QDDs2V2V-WsIOYTotIzemftJR4',
//     appId: '1:670079218783:web:85bcec61bd7029fbb497ea',
//     messagingSenderId: '670079218783',
//     projectId: 'lsp-ps',
//     authDomain: 'lsp-ps.firebaseapp.com',
//     storageBucket: 'lsp-ps.appspot.com',
//     measurementId: 'G-4543ZVD8P6',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAuyzVm9Wp_V6Hxw1Ux9KeBIww9vJP28SQ',
//     appId: '1:670079218783:android:8e7e09298658aecfb497ea',
//     messagingSenderId: '670079218783',
//     projectId: 'lsp-ps',
//     storageBucket: 'lsp-ps.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyALQ3xlGqOvvIDS8UE9RshNnI3oJX4dPDk',
//     appId: '1:670079218783:ios:67b1f0b357c1ca9cb497ea',
//     messagingSenderId: '670079218783',
//     projectId: 'lsp-ps',
//     storageBucket: 'lsp-ps.appspot.com',
//     iosClientId: '670079218783-9lep3rcm59lbpfe94bi86velirhv1hur.apps.googleusercontent.com',
//     iosBundleId: 'com.rynest.aasi',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyALQ3xlGqOvvIDS8UE9RshNnI3oJX4dPDk',
//     appId: '1:670079218783:ios:67b1f0b357c1ca9cb497ea',
//     messagingSenderId: '670079218783',
//     projectId: 'lsp-ps',
//     storageBucket: 'lsp-ps.appspot.com',
//     iosClientId: '670079218783-9lep3rcm59lbpfe94bi86velirhv1hur.apps.googleusercontent.com',
//     iosBundleId: 'com.rynest.aasi',
//   );
// }
